# Generated by Django 5.1.7 on 2025-03-21 12:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='DDIProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('start_date', models.DateField()),
                ('planned_duration', models.CharField(max_length=50)),
                ('sit_start_date', models.DateField()),
                ('sit_end_date', models.DateField()),
                ('uat_start_date', models.DateField()),
                ('uat_end_date', models.DateField()),
                ('go_live_date', models.DateField()),
                ('history', models.TextField()),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ddiprofile.state')),
            ],
        ),
    ]
