# Generated by Django 5.1.7 on 2025-03-21 13:26

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ddiprofile', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DDIPhases',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='ddiprofile',
            name='history',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='DDIStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('sit_complete', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('uat_complete', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('current_phase', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ddiprofile.ddiphases')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ddiprofile.ddiprofile')),
            ],
        ),
    ]
