# Generated by Django 5.1.7 on 2025-03-26 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ddiprofile', '0002_ddiphases_alter_ddiprofile_history_ddistatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ddistatus',
            name='sit_complete',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=3),
        ),
        migrations.AlterField(
            model_name='ddistatus',
            name='uat_complete',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=3),
        ),
    ]
