# Generated by Django 5.1.7 on 2025-04-07 17:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ddiprofile', '0003_alter_ddistatus_sit_complete_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Initiative',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('workitemtype', models.CharField(max_length=50)),
                ('currentphase', models.CharField(blank=True, max_length=100, null=True)),
                ('golivedate', models.DateField(blank=True, null=True)),
                ('months', models.IntegerField(blank=True, null=True)),
                ('sitcmpl', models.FloatField(blank=True, null=True)),
                ('sitstart', models.DateField(blank=True, null=True)),
                ('start', models.DateField(blank=True, null=True)),
                ('uatcmpl', models.FloatField(blank=True, null=True)),
                ('uatstart', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Epic',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('workitemtype', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('areapath', models.CharField(max_length=255)),
                ('created_date', models.DateField()),
                ('initiative', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='epics', to='ddiprofile.initiative')),
            ],
        ),
    ]
