# Generated by Django 5.1.7 on 2025-04-07 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ddiprofile', '0004_initiative_epic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='epic',
            name='created_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
