# Generated by Django 5.1.7 on 2025-04-07 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ddiprofile', '0005_alter_epic_created_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='LastRefeshed',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('date', models.DateTimeField()),
            ],
        ),
        migrations.AddField(
            model_name='epic',
            name='enddate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='epic',
            name='epiccategory',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='epic',
            name='iterationpath',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='epic',
            name='requiredbdate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='epic',
            name='statuschoice',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='epic',
            name='statustextbox',
            field=models.TextField(blank=True, null=True),
        ),
    ]
