# Generated by Django 5.1.7 on 2025-04-07 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ddiprofile', '0006_lastrefeshed_epic_enddate_epic_epiccategory_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LastRefeshed',
            new_name='LastRefreshed',
        ),
    ]
