# Generated by Django 5.1.7 on 2025-04-07 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ddiprofile', '0007_rename_lastrefeshed_lastrefreshed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lastrefreshed',
            name='date',
        ),
    ]
