# Generated by Django 5.1.7 on 2025-04-07 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ddiprofile', '0008_remove_lastrefreshed_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='epic',
            name='areapath',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
