# Generated by Django 5.1.7 on 2025-04-08 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ddiprofile', '0009_alter_epic_areapath'),
    ]

    operations = [
        migrations.AlterField(
            model_name='initiative',
            name='sitcmpl',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=3),
        ),
        migrations.AlterField(
            model_name='initiative',
            name='uatcmpl',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=3),
        ),
    ]
