# Generated by Django 5.1.7 on 2025-04-08 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ddiprofile', '0010_alter_initiative_sitcmpl_alter_initiative_uatcmpl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='initiative',
            name='sitcmpl',
            field=models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=3, null=True),
        ),
        migrations.AlterField(
            model_name='initiative',
            name='uatcmpl',
            field=models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=3, null=True),
        ),
    ]
