# Generated by Django 5.1.7 on 2025-04-08 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ddiprofile', '0011_alter_initiative_sitcmpl_alter_initiative_uatcmpl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='initiative',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
