# Generated by Django 5.1.7 on 2025-04-08 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ddiprofile', '0012_alter_initiative_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='epic',
            name='state',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='epic',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='epic',
            name='workitemtype',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='initiative',
            name='workitemtype',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
