# Generated by Django 5.1.7 on 2025-04-08 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ddiprofile', '0013_alter_epic_state_alter_epic_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='epic',
            name='state',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='epic',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='epic',
            name='workitemtype',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='initiative',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='initiative',
            name='workitemtype',
            field=models.CharField(max_length=50),
        ),
    ]
