# Generated by Django 5.2 on 2025-04-24 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ddiprofile", "0014_alter_epic_state_alter_epic_title_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ddistatus",
            name="current_phase",
        ),
        migrations.RemoveField(
            model_name="ddiprofile",
            name="state",
        ),
        migrations.RemoveField(
            model_name="ddistatus",
            name="name",
        ),
        migrations.DeleteModel(
            name="DDIPhases",
        ),
        migrations.DeleteModel(
            name="State",
        ),
        migrations.DeleteModel(
            name="DDIProfile",
        ),
        migrations.DeleteModel(
            name="DDIStatus",
        ),
    ]
