# Generated by Django 5.2 on 2025-04-25 16:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ddiprofile", "0015_remove_ddistatus_current_phase_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="initiative",
            name="clientaccounts",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="initiative",
            name="solutiongotomarket",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.CreateModel(
            name="ChangeRequest",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=255)),
                ("workitemtype", models.CharField(max_length=50)),
                ("state", models.CharField(max_length=50)),
                ("areapath", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "iterationpath",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "clientaccounts",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "solutiongotomarket",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("targetdate", models.DateField(blank=True, null=True)),
                (
                    "highlevelestimate",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "tt_initiative",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "tt_workdescription",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "tt_workcategory",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("tt_capwbs", models.CharField(blank=True, max_length=255, null=True)),
                ("tt_expwbs", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "tt_onshorewbs",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "tt_offshorewbs",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "initiative",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="change_requests",
                        to="ddiprofile.initiative",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Feature",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=255)),
                ("workitemtype", models.CharField(max_length=50)),
                ("state", models.CharField(max_length=50)),
                ("areapath", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "iterationpath",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "clientaccounts",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "solutiongotomarket",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("startdate", models.DateField(blank=True, null=True)),
                ("targetdate", models.DateField(blank=True, null=True)),
                (
                    "highlevelestimate",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "tt_initiative",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "tt_workcategory",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "tt_workdescription",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("tt_capwbs", models.CharField(blank=True, max_length=255, null=True)),
                ("tt_expwbs", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "tt_onshorewbs",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "tt_offshorewbs",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "cr_related",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="features",
                        to="ddiprofile.changerequest",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UserStory",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=255)),
                ("workitemtype", models.CharField(max_length=50)),
                ("state", models.CharField(max_length=50)),
                ("areapath", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "iterationpath",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "clientaccounts",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "storypoints",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "tt_initiative",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "tt_workcategory",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "tt_workdescription",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("tt_capwbs", models.CharField(blank=True, max_length=255, null=True)),
                ("tt_expwbs", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "tt_onshorewbs",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "tt_offshorewbs",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "feature_related",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_stories",
                        to="ddiprofile.feature",
                    ),
                ),
            ],
        ),
    ]
