# Generated by Django 5.2 on 2025-04-29 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ddiprofile", "0016_initiative_clientaccounts_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Iteration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("iteration_id", models.CharField(max_length=100, unique=True)),
                ("name", models.CharField(max_length=255)),
                ("path", models.CharField(max_length=255)),
                ("start_date", models.DateField(blank=True, null=True)),
                ("finish_date", models.DateField(blank=True, null=True)),
                ("time_frame", models.CharField(max_length=50)),
            ],
        ),
    ]
