# Generated by Django 5.2 on 2025-04-29 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ddiprofile", "0017_iteration"),
    ]

    operations = [
        migrations.AlterField(
            model_name="iteration",
            name="time_frame",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
