# Generated by Django 5.2 on 2025-04-29 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ddiprofile", "0018_alter_iteration_time_frame"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="iteration",
            name="time_frame",
        ),
    ]
