# Generated by Django 5.2 on 2025-04-29 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ddiprofile", "0019_remove_iteration_time_frame"),
    ]

    operations = [
        migrations.AddField(
            model_name="iteration",
            name="scriptupdated",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
