# Generated by Django 5.2 on 2025-04-29 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ddiprofile", "0020_iteration_scriptupdated"),
    ]

    operations = [
        migrations.AlterField(
            model_name="iteration",
            name="scriptupdated",
            field=models.CharField(max_length=255),
        ),
    ]
