# Generated by Django 5.2 on 2025-05-01 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ddiprofile", "0021_alter_iteration_scriptupdated"),
    ]

    operations = [
        migrations.AddField(
            model_name="changerequest",
            name="createddate",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="feature",
            name="createddate",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="userstory",
            name="createddate",
            field=models.DateField(blank=True, null=True),
        ),
    ]
