# Generated by Django 5.2 on 2025-05-01 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ddiprofile", "0022_changerequest_createddate_feature_createddate_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="changerequest",
            name="requiredbdate",
            field=models.DateField(blank=True, null=True),
        ),
    ]
