# Generated by Django 5.2 on 2025-05-01 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ddiprofile", "0023_changerequest_requiredbdate"),
    ]

    operations = [
        migrations.RenameField(
            model_name="changerequest",
            old_name="requiredbdate",
            new_name="requiredbydate",
        ),
        migrations.RenameField(
            model_name="epic",
            old_name="requiredbdate",
            new_name="requiredbydate",
        ),
    ]
