# Generated by Django 5.2 on 2025-05-12 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "ddiprofile",
            "0024_rename_requiredbdate_changerequest_requiredbydate_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="initiative",
            name="deliverysupportdirector",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="initiative",
            name="deliverysupportleader",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="initiative",
            name="deliverysupportseniorleader",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
