# Generated by Django 5.2 on 2025-05-12 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ddiprofile", "0025_initiative_deliverysupportdirector_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="initiative",
            name="deliverysupportdirectormail",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="initiative",
            name="deliverysupportleadermail",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="initiative",
            name="deliverysupportseniorleadermail",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
