# Generated by Django 5.2 on 2025-05-19 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ddiprofile", "0026_initiative_deliverysupportdirectormail_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="initiative",
            name="deliverysupportdirectormail",
        ),
        migrations.RemoveField(
            model_name="initiative",
            name="deliverysupportleadermail",
        ),
        migrations.RemoveField(
            model_name="initiative",
            name="deliverysupportseniorleadermail",
        ),
        migrations.AddField(
            model_name="initiative",
            name="sitend",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="initiative",
            name="uatend",
            field=models.DateField(blank=True, null=True),
        ),
    ]
