# Generated by Django 5.2 on 2025-05-19 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ddiprofile", "0027_remove_initiative_deliverysupportdirectormail_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="changerequest",
            name="initiative",
        ),
        migrations.AddField(
            model_name="changerequest",
            name="initiatives",
            field=models.ManyToManyField(
                related_name="change_requests", to="ddiprofile.initiative"
            ),
        ),
    ]
