# Generated by Django 5.2 on 2025-05-19 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ddiprofile", "0028_remove_changerequest_initiative_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Epic",
        ),
    ]
