# Generated by Django 5.2 on 2025-05-27 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "ddiprofile",
            "0030_crepic_crlastrefreshed_crchangerequest_crfeature_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="WBSInformation",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("employee_id", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "employee_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("workdate", models.DateField(blank=True, null=True)),
                (
                    "effort",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        default=0.0,
                        max_digits=10,
                        null=True,
                    ),
                ),
                ("atype", models.CharField(blank=True, max_length=50, null=True)),
                ("atypetext", models.CharField(blank=True, max_length=255, null=True)),
                ("wbs", models.CharField(max_length=255, unique=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("initiative", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "workcategory",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "workdescription",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("module", models.CharField(blank=True, max_length=255, null=True)),
                ("backlog", models.CharField(blank=True, max_length=255, null=True)),
                ("wbstype", models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
