# Generated by Django 5.2 on 2025-05-27 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ddiprofile", "0031_wbsinformation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="wbsinformation",
            name="wbs",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
