# Generated by Django 5.2 on 2025-05-28 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ddiprofile", "0032_alter_wbsinformation_wbs"),
    ]

    operations = [
        migrations.AddField(
            model_name="wbsinformation",
            name="monthyear",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
