# Generated by Django 5.2 on 2025-05-28 13:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ddiprofile", "0033_wbsinformation_monthyear"),
    ]

    operations = [
        migrations.CreateModel(
            name="crTask",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=255)),
                ("workitemtype", models.CharField(max_length=50)),
                ("state", models.CharField(max_length=50)),
                ("areapath", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "iterationpath",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "storypoints",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "originalestimate",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "remainingwork",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "completedwork",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "userstory_related",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tasks",
                        to="ddiprofile.cruserstory",
                    ),
                ),
            ],
        ),
    ]
