# Generated by Django 5.2 on 2025-06-09 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ddiprofile", "0034_crtask"),
    ]

    operations = [
        migrations.AddField(
            model_name="lastrefreshed",
            name="datetime",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
