# Generated by Django 5.2 on 2025-06-09 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ddiprofile", "0035_lastrefreshed_datetime"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="lastrefreshed",
            name="datetime",
        ),
    ]
