# Generated by Django 5.2 on 2025-06-12 14:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ddiprofile", "0036_remove_lastrefreshed_datetime"),
    ]

    operations = [
        migrations.CreateModel(
            name="gapEpic",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=255)),
                ("workitemtype", models.CharField(max_length=50)),
                ("state", models.CharField(max_length=50)),
                ("areapath", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "iterationpath",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("enddate", models.DateField(blank=True, null=True)),
                (
                    "statuschoice",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("statustextbox", models.TextField(blank=True, null=True)),
                ("requiredbdate", models.DateField(blank=True, null=True)),
                (
                    "epiccategory",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("created_date", models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="gapLastRefreshed",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="gapChangeRequest",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=255)),
                ("workitemtype", models.CharField(max_length=50)),
                ("state", models.CharField(max_length=50)),
                ("areapath", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "iterationpath",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "clientaccounts",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("targetdate", models.DateField(blank=True, null=True)),
                (
                    "highlevelestimate",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "tt_initiative",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "tt_workdescription",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "tt_workcategory",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("tt_capwbs", models.CharField(blank=True, max_length=255, null=True)),
                ("tt_expwbs", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "tt_onshorewbs",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "tt_offshorewbs",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("epicnumber", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "epicparent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ddiprofile.gapepic",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="gapFeature",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=255)),
                ("workitemtype", models.CharField(max_length=50)),
                ("state", models.CharField(max_length=50)),
                ("areapath", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "iterationpath",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "clientaccounts",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("startdate", models.DateField(blank=True, null=True)),
                ("targetdate", models.DateField(blank=True, null=True)),
                (
                    "highlevelestimate",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "tt_initiative",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "tt_workcategory",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "tt_workdescription",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("tt_capwbs", models.CharField(blank=True, max_length=255, null=True)),
                ("tt_expwbs", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "tt_onshorewbs",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "tt_offshorewbs",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "cr_related",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="features",
                        to="ddiprofile.gapchangerequest",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="gapUserStory",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=255)),
                ("workitemtype", models.CharField(max_length=50)),
                ("state", models.CharField(max_length=50)),
                ("areapath", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "iterationpath",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "clientaccounts",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "storypoints",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "tt_initiative",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "tt_workcategory",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "tt_workdescription",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("tt_capwbs", models.CharField(blank=True, max_length=255, null=True)),
                ("tt_expwbs", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "tt_onshorewbs",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "tt_offshorewbs",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "feature_related",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_stories",
                        to="ddiprofile.gapfeature",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="gapTask",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=255)),
                ("workitemtype", models.CharField(max_length=50)),
                ("state", models.CharField(max_length=50)),
                ("areapath", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "iterationpath",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "storypoints",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "originalestimate",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "remainingwork",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "completedwork",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "userstory_related",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tasks",
                        to="ddiprofile.gapuserstory",
                    ),
                ),
            ],
        ),
    ]
