from django.db import models
from django.core.exceptions import ValidationError
from django.utils import timezone


# DDI Dashboard Models
class Initiative(models.Model):
    id = models.IntegerField(primary_key=True)
    title = models.CharField(max_length=255)
    workitemtype = models.CharField(max_length=50)
    currentphase = models.CharField(max_length=100, blank=True, null=True)
    golivedate = models.DateField(blank=True, null=True)
    months = models.IntegerField(blank=True, null=True)
    sitcmpl = models.DecimalField(default=0, decimal_places=0, max_digits=3, blank=True, null=True)
    sitstart = models.DateField(blank=True, null=True)
    sitend = models.DateField(blank=True, null=True)
    start = models.DateField(blank=True, null=True)
    uatcmpl = models.DecimalField(default=0, decimal_places=0, max_digits=3, blank=True, null=True)
    uatstart = models.DateField(blank=True, null=True)
    uatend = models.DateField(blank=True, null=True)
    clientaccounts = models.CharField(max_length=255, blank=True, null=True)
    solutiongotomarket = models.CharField(max_length=255, blank=True, null=True)
    deliverysupportleader = models.CharField(max_length=255, blank=True, null=True)
    deliverysupportseniorleader = models.CharField(max_length=255, blank=True, null=True)
    deliverysupportdirector = models.CharField(max_length=255, blank=True, null=True)

class ChangeRequest(models.Model):
    id = models.IntegerField(primary_key=True)
    title = models.CharField(max_length=255)
    workitemtype = models.CharField(max_length=50)
    state = models.CharField(max_length=50)
    areapath = models.CharField(max_length=255, blank=True, null=True)
    iterationpath = models.CharField(max_length=255, blank=True, null=True)
    clientaccounts = models.CharField(max_length=255, blank=True, null=True)
    solutiongotomarket = models.CharField(max_length=255, blank=True, null=True)
    targetdate = models.DateField(blank=True, null=True)
    highlevelestimate = models.CharField(max_length=255, blank=True, null=True)
    tt_initiative = models.CharField(max_length=255, blank=True, null=True)
    tt_workdescription = models.CharField(max_length=255, blank=True, null=True)
    tt_workcategory = models.CharField(max_length=255, blank=True, null=True)
    tt_capwbs = models.CharField(max_length=255, blank=True, null=True)
    tt_expwbs = models.CharField(max_length=255, blank=True, null=True)
    tt_onshorewbs = models.CharField(max_length=255, blank=True, null=True)
    tt_offshorewbs = models.CharField(max_length=255, blank=True, null=True)
    createddate = models.DateField(blank=True, null=True)
    requiredbydate = models.DateField(blank=True, null=True)
    initiatives = models.ManyToManyField('Initiative', related_name='change_requests')

class Feature(models.Model):
    id = models.IntegerField(primary_key=True)
    title = models.CharField(max_length=255)
    workitemtype = models.CharField(max_length=50)
    state = models.CharField(max_length=50)
    areapath = models.CharField(max_length=255, blank=True, null=True)
    iterationpath = models.CharField(max_length=255, blank=True, null=True)
    clientaccounts = models.CharField(max_length=255, blank=True, null=True)
    solutiongotomarket = models.CharField(max_length=255, blank=True, null=True)
    startdate = models.DateField(blank=True, null=True)
    targetdate = models.DateField(blank=True, null=True)
    highlevelestimate = models.CharField(max_length=255, blank=True, null=True)
    tt_initiative = models.CharField(max_length=255, blank=True, null=True)
    tt_workcategory = models.CharField(max_length=255, blank=True, null=True)
    tt_workdescription = models.CharField(max_length=255, blank=True, null=True)
    tt_capwbs = models.CharField(max_length=255, blank=True, null=True)
    tt_expwbs = models.CharField(max_length=255, blank=True, null=True)
    tt_onshorewbs = models.CharField(max_length=255, blank=True, null=True)
    tt_offshorewbs = models.CharField(max_length=255, blank=True, null=True)
    createddate = models.DateField(blank=True, null=True)
    cr_related = models.ForeignKey(ChangeRequest, on_delete=models.CASCADE, related_name='features')

class UserStory(models.Model):
    id = models.IntegerField(primary_key=True)
    title = models.CharField(max_length=255)
    workitemtype = models.CharField(max_length=50)
    state = models.CharField(max_length=50)
    areapath = models.CharField(max_length=255, blank=True, null=True)
    iterationpath = models.CharField(max_length=255, blank=True, null=True)
    clientaccounts = models.CharField(max_length=255, blank=True, null=True)
    storypoints = models.CharField(max_length=255, blank=True, null=True)
    tt_initiative = models.CharField(max_length=255, blank=True, null=True)
    tt_workcategory = models.CharField(max_length=255, blank=True, null=True)
    tt_workdescription = models.CharField(max_length=255, blank=True, null=True)
    tt_capwbs = models.CharField(max_length=255, blank=True, null=True)
    tt_expwbs = models.CharField(max_length=255, blank=True, null=True)
    tt_onshorewbs = models.CharField(max_length=255, blank=True, null=True)
    tt_offshorewbs = models.CharField(max_length=255, blank=True, null=True)
    createddate = models.DateField(blank=True, null=True)
    feature_related = models.ForeignKey(Feature, on_delete=models.CASCADE,related_name='user_stories')

class LastRefreshed(models.Model):
    id = models.IntegerField(primary_key=True)
    title = models.CharField(max_length=255)

class Iteration(models.Model):
    iteration_id = models.CharField(max_length=100, unique=True)  # Unique ID from Azure
    name = models.CharField(max_length=255)  # Iteration name
    path = models.CharField(max_length=255)  # Iteration path
    start_date = models.DateField(null=True, blank=True)  # Start date
    finish_date = models.DateField(null=True, blank=True)  # Finish date
    scriptupdated = models.CharField(max_length=255)  # Last updated timestamp

#CR Dashboard Models
class crEpic(models.Model):
    id = models.IntegerField(primary_key=True)
    title = models.CharField(max_length=255)
    workitemtype = models.CharField(max_length=50)
    state = models.CharField(max_length=50)
    areapath = models.CharField(max_length=255, blank=True, null=True)
    iterationpath = models.CharField(max_length=255, blank=True, null=True)
    enddate = models.DateField(blank=True, null=True)
    statuschoice = models.CharField(max_length=100, blank=True, null=True)
    statustextbox = models.TextField(blank=True, null=True)
    requiredbdate = models.DateField(blank=True, null=True)
    epiccategory = models.CharField(max_length=100, blank=True, null=True)
    created_date = models.DateField(blank=True, null=True)

class crChangeRequest(models.Model):
    id = models.IntegerField(primary_key=True)
    title = models.CharField(max_length=255)
    workitemtype = models.CharField(max_length=50)
    state = models.CharField(max_length=50)
    areapath = models.CharField(max_length=255, blank=True, null=True)
    iterationpath = models.CharField(max_length=255, blank=True, null=True)
    clientaccounts = models.CharField(max_length=255, blank=True, null=True)
    targetdate = models.DateField(blank=True, null=True)
    highlevelestimate = models.CharField(max_length=255, blank=True, null=True)
    tt_initiative = models.CharField(max_length=255, blank=True, null=True)
    tt_workdescription = models.CharField(max_length=255, blank=True, null=True)
    tt_workcategory = models.CharField(max_length=255, blank=True, null=True)
    tt_capwbs = models.CharField(max_length=255, blank=True, null=True)
    tt_expwbs = models.CharField(max_length=255, blank=True, null=True)
    tt_onshorewbs = models.CharField(max_length=255, blank=True, null=True)
    tt_offshorewbs = models.CharField(max_length=255, blank=True, null=True)
    epicparent = models.ForeignKey(crEpic, on_delete=models.CASCADE, blank=True, null=True)
    epicnumber = models.CharField(max_length=255, blank=True, null=True)

class crFeature(models.Model):
    id = models.IntegerField(primary_key=True)
    title = models.CharField(max_length=255)
    workitemtype = models.CharField(max_length=50)
    state = models.CharField(max_length=50)
    areapath = models.CharField(max_length=255, blank=True, null=True)
    iterationpath = models.CharField(max_length=255, blank=True, null=True)
    clientaccounts = models.CharField(max_length=255, blank=True, null=True)
    startdate = models.DateField(blank=True, null=True)
    targetdate = models.DateField(blank=True, null=True)
    highlevelestimate = models.CharField(max_length=255, blank=True, null=True)
    tt_initiative = models.CharField(max_length=255, blank=True, null=True)
    tt_workcategory = models.CharField(max_length=255, blank=True, null=True)
    tt_workdescription = models.CharField(max_length=255, blank=True, null=True)
    tt_capwbs = models.CharField(max_length=255, blank=True, null=True)
    tt_expwbs = models.CharField(max_length=255, blank=True, null=True)
    tt_onshorewbs = models.CharField(max_length=255, blank=True, null=True)
    tt_offshorewbs = models.CharField(max_length=255, blank=True, null=True)
    cr_related = models.ForeignKey(crChangeRequest, on_delete=models.CASCADE, related_name='features')

class crUserStory(models.Model):
    id = models.IntegerField(primary_key=True)
    title = models.CharField(max_length=255)
    workitemtype = models.CharField(max_length=50)
    state = models.CharField(max_length=50)
    areapath = models.CharField(max_length=255, blank=True, null=True)
    iterationpath = models.CharField(max_length=255, blank=True, null=True)
    clientaccounts = models.CharField(max_length=255, blank=True, null=True)
    storypoints = models.CharField(max_length=255, blank=True, null=True)
    tt_initiative = models.CharField(max_length=255, blank=True, null=True)
    tt_workcategory = models.CharField(max_length=255, blank=True, null=True)
    tt_workdescription = models.CharField(max_length=255, blank=True, null=True)
    tt_capwbs = models.CharField(max_length=255, blank=True, null=True)
    tt_expwbs = models.CharField(max_length=255, blank=True, null=True)
    tt_onshorewbs = models.CharField(max_length=255, blank=True, null=True)
    tt_offshorewbs = models.CharField(max_length=255, blank=True, null=True)
    feature_related = models.ForeignKey(crFeature, on_delete=models.CASCADE,related_name='user_stories')

class crLastRefreshed(models.Model):
    id = models.IntegerField(primary_key=True)
    title = models.CharField(max_length=255)

#WBS Information Models
class WBSInformation(models.Model):
    id = models.IntegerField(primary_key=True)
    employee_id = models.CharField(max_length=50, blank=True, null=True)
    employee_name = models.CharField(max_length=255, blank=True, null=True)
    workdate = models.DateField(blank=True, null=True)
    effort = models.DecimalField(max_digits=10, decimal_places=2, default=0.00, blank=True, null=True)
    atype = models.CharField(max_length=50, blank=True, null=True)
    atypetext = models.CharField(max_length=255, blank=True, null=True)
    wbs = models.CharField(max_length=255, blank=True, null=True)
    description = models.TextField(blank=True, null=True)
    initiative = models.CharField(max_length=255, blank=True, null=True)
    workcategory = models.CharField(max_length=255, blank=True, null=True)
    workdescription = models.CharField(max_length=255, blank=True, null=True)
    module = models.CharField(max_length=255, blank=True, null=True)
    backlog = models.CharField(max_length=255, blank=True, null=True)
    wbstype = models.CharField(max_length=50, blank=True, null=True)
    monthyear = models.CharField(max_length=50, blank=True, null=True)